In [9]:
# load neccessary modules
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt 

# load data
df = pd.read_csv("data/input.csv")

# Take columns of interest only (can add more later on)
columns_of_interest = [
    'price', 
    'property_type',
    'province',
    'zip_code',
    'subproperty_type',
    'total_area_sqm',
    'nbr_bedrooms',
    'fl_terrace',
    'fl_garden',
    'state_building',
    'primary_energy_consumption_sqm',
]

new_df = df[columns_of_interest]

# fill missing columns here
mean_sqm_per_category = df.groupby('property_type')['total_area_sqm'].mean()

new_df['total_area_sqm'] = df.apply(
    lambda row: mean_sqm_per_category[row['property_type']] if pd.isna(row['total_area_sqm']) else row['total_area_sqm'],
    axis=1
)

median_energy_consumption_sqm = new_df.groupby(["property_type", "zip_code"])["primary_energy_consumption_sqm"].transform("median")

new_df['primary_energy_consumption_sqm'].fillna(median_energy_consumption_sqm, inplace=True)

new_df.info()

# new_df.dropna(subset=["province"], inplace=True)

KeyError: ['province']

In [139]:
# Qualitative -> Quantitative
new_df["property_type"] = new_df['property_type'].replace({'HOUSE': 1, 'APARTMENT': 0}) 

new_df = pd.get_dummies(new_df, columns=["subproperty_type"])

new_df = pd.get_dummies(new_df, columns=["province"])

new_df = pd.get_dummies(new_df, columns=["state_building"])
# Converts true/false to 1/0
new_df = new_df * 1


# Calculate the correlation coefficient
correlation = new_df['total_area_sqm'].corr(new_df['price'])

# Print the correlation coefficient
print(f"Correlation between 'feature' and 'price': {correlation}")

Correlation between 'feature' and 'price': 0.18670253556383215

/var/folders/71/3p_b411j49jblf0447_3sy840000gp/T/ipykernel_33254/3230854210.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new_df["property_type"] = new_df['property_type'].replace({'HOUSE': 1, 'APARTMENT': 0})
/var/folders/71/3p_b411j49jblf0447_3sy840000gp/T/ipykernel_33254/3230854210.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["property_type"] = new_df['property_type'].replace({'HOUSE': 1, 'APARTMENT': 0})

In [140]:
# Set display options to show all columns
pd.set_option('display.max_columns', None)

# Drop col
new_df = new_df.drop("province_MISSING", axis=1)

# Displays the first 5 rows of the data set
new_df.head(25)

,price,property_type,zip_code,total_area_sqm,nbr_bedrooms,fl_terrace,fl_garden,primary_energy_consumption_sqm,subproperty_type_APARTMENT,subproperty_type_APARTMENT_BLOCK,subproperty_type_BUNGALOW,subproperty_type_CASTLE,subproperty_type_CHALET,subproperty_type_COUNTRY_COTTAGE,subproperty_type_DUPLEX,subproperty_type_EXCEPTIONAL_PROPERTY,subproperty_type_FARMHOUSE,subproperty_type_FLAT_STUDIO,subproperty_type_GROUND_FLOOR,subproperty_type_HOUSE,subproperty_type_KOT,subproperty_type_LOFT,subproperty_type_MANOR_HOUSE,subproperty_type_MANSION,subproperty_type_MIXED_USE_BUILDING,subproperty_type_OTHER_PROPERTY,subproperty_type_PENTHOUSE,subproperty_type_SERVICE_FLAT,subproperty_type_TOWN_HOUSE,subproperty_type_TRIPLEX,subproperty_type_VILLA,province_Antwerp,province_Brussels,province_East Flanders,province_Flemish Brabant,province_Hainaut,province_Limburg,province_Liège,province_Luxembourg,province_Namur,province_Walloon Brabant,province_West Flanders,state_building_AS_NEW,state_building_GOOD,state_building_JUST_RENOVATED,state_building_MISSING,state_building_TO_BE_DONE_UP,state_building_TO_RENOVATE,state_building_TO_RESTORE
0,225000.0,0,2050,100.000000,2.0,1,0,231.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,449000.0,1,9185,223.261114,2.0,0,0,221.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,335000.0,0,1070,142.000000,3.0,1,0,201.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
3,501000.0,1,2275,187.000000,3.0,0,0,99.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,982700.0,0,1410,169.000000,2.0,1,1,19.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0
5,548514.0,1,1700,187.000000,3.0,0,0,339.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0
6,325000.0,0,1420,80.000000,1.0,1,0,93.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0
7,424000.0,1,9800,155.000000,4.0,0,0,213.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
8,185000.0,0,4000,104.097929,2.0,1,0,212.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0
9,3500000.0,1,8300,277.000000,6.0,0,0,394.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
10,385000.0,1,9190,309.000000,3.0,0,0,305.5,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
11,957000.0,0,8670,133.000000,3.0,1,0,154.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0
12,294000.0,0,4700,106.000000,2.0,1,0,221.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0
13,347000.0,0,2820,102.000000,2.0,1,0,113.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
14,110000.0,1,6010,150.000000,2.0,1,0,386.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
15,920000.0,1,8670,223.261114,4.0,1,0,139.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0
16,258000.0,0,4620,83.000000,1.0,1,0,50.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0
17,499000.0,1,4040,223.261114,7.0,1,0,200.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0
18,270000.0,0,2100,115.000000,3.0,1,0,236.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
19,1495000.0,1,1083,583.000000,5.0,1,0,498.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
20,549000.0,1,9240,185.000000,4.0,0,0,142.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
21,450000.0,1,1070,150.000000,3.0,1,1,322.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
22,175000.0,0,1160,38.000000,0.0,0,0,265.0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
23,272000.0,0,1500,84.000000,2.0,1,0,245.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0
24,298500.0,1,6637,160.000000,3.0,0,1,287.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0

In [141]:
# df.subproperty_type.value_counts()

new_df.info()

new_df.to_csv("data/properties_ml.csv")

print("Modified CSV file saved successfully.")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75511 entries, 0 to 75510
Data columns (total 49 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   price                                  75511 non-null  float64
 1   property_type                          75511 non-null  int64
 2   zip_code                               75511 non-null  int64
 3   total_area_sqm                         75511 non-null  float64
 4   nbr_bedrooms                           75511 non-null  float64
 5   fl_terrace                             75511 non-null  int64
 6   fl_garden                              75511 non-null  int64
 7   primary_energy_consumption_sqm         75122 non-null  float64
 8   subproperty_type_APARTMENT             75511 non-null  int64
 9   subproperty_type_APARTMENT_BLOCK       75511 non-null  int64
 10  subproperty_type_BUNGALOW              75511 non-null  int64
 11  subproperty_type_CASTLE                75511 non-null  int64
 12  subproperty_type_CHALET                75511 non-null  int64
 13  subproperty_type_COUNTRY_COTTAGE       75511 non-null  int64
 14  subproperty_type_DUPLEX                75511 non-null  int64
 15  subproperty_type_EXCEPTIONAL_PROPERTY  75511 non-null  int64
 16  subproperty_type_FARMHOUSE             75511 non-null  int64
 17  subproperty_type_FLAT_STUDIO           75511 non-null  int64
 18  subproperty_type_GROUND_FLOOR          75511 non-null  int64
 19  subproperty_type_HOUSE                 75511 non-null  int64
 20  subproperty_type_KOT                   75511 non-null  int64
 21  subproperty_type_LOFT                  75511 non-null  int64
 22  subproperty_type_MANOR_HOUSE           75511 non-null  int64
 23  subproperty_type_MANSION               75511 non-null  int64
 24  subproperty_type_MIXED_USE_BUILDING    75511 non-null  int64
 25  subproperty_type_OTHER_PROPERTY        75511 non-null  int64
 26  subproperty_type_PENTHOUSE             75511 non-null  int64
 27  subproperty_type_SERVICE_FLAT          75511 non-null  int64
 28  subproperty_type_TOWN_HOUSE            75511 non-null  int64
 29  subproperty_type_TRIPLEX               75511 non-null  int64
 30  subproperty_type_VILLA                 75511 non-null  int64
 31  province_Antwerp                       75511 non-null  int64
 32  province_Brussels                      75511 non-null  int64
 33  province_East Flanders                 75511 non-null  int64
 34  province_Flemish Brabant               75511 non-null  int64
 35  province_Hainaut                       75511 non-null  int64
 36  province_Limburg                       75511 non-null  int64
 37  province_Liège                         75511 non-null  int64
 38  province_Luxembourg                    75511 non-null  int64
 39  province_Namur                         75511 non-null  int64
 40  province_Walloon Brabant               75511 non-null  int64
 41  province_West Flanders                 75511 non-null  int64
 42  state_building_AS_NEW                  75511 non-null  int64
 43  state_building_GOOD                    75511 non-null  int64
 44  state_building_JUST_RENOVATED          75511 non-null  int64
 45  state_building_MISSING                 75511 non-null  int64
 46  state_building_TO_BE_DONE_UP           75511 non-null  int64
 47  state_building_TO_RENOVATE             75511 non-null  int64
 48  state_building_TO_RESTORE              75511 non-null  int64
dtypes: float64(4), int64(45)
memory usage: 28.2 MB
Modified CSV file saved successfully.